#!/usr/bin/env bash
# setup-org.sh — Prompt for the Docker org name and store it for use by the labs.
# Writes to /project/setup/.env which is sourced by other lab scripts.
#
# Re-run any time to change the org.

set -eu

SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SETUP_DIR}/.env"

cat <<'EOF'

╭────────────────────────────────────────────────────────────╮
│  Docker AI Governance Labspace — Setup                     │
╰────────────────────────────────────────────────────────────╯

Tell us about your Docker org so we can personalise the labs.
This is used to substitute domain placeholders (e.g. *.acme.example
becomes *.your-org.example) in Labs 5, 7, and 8.

Examples:
  - bosch
  - acme-corp
  - mycompany

EOF

# Prompt — but accept a default for non-interactive contexts
DEFAULT_ORG="acme-corp"
if [[ -t 0 ]]; then
  read -r -p "Your Docker org name (default: ${DEFAULT_ORG}): " ORG
else
  ORG=""
fi
ORG="${ORG:-$DEFAULT_ORG}"

# Sanitise — alphanumeric + hyphens only
SAFE_ORG=$(echo "$ORG" | tr -cd 'a-zA-Z0-9-' | tr '[:upper:]' '[:lower:]')
if [[ -z "$SAFE_ORG" ]]; then
  SAFE_ORG="$DEFAULT_ORG"
fi

# Internal domain placeholder follows from the org name
INTERNAL_DOMAIN="${SAFE_ORG}-internal.example"

# Optional — capture the email domain for audit examples
if [[ -t 0 ]]; then
  read -r -p "Your email domain (default: ${SAFE_ORG}.example): " EMAIL_DOMAIN
else
  EMAIL_DOMAIN=""
fi
EMAIL_DOMAIN="${EMAIL_DOMAIN:-${SAFE_ORG}.example}"

# Write the env file
cat > "$ENV_FILE" <<EOF
# Generated by setup-org.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Re-run setup-org.sh any time to change.

DOCKER_ORG="${SAFE_ORG}"
INTERNAL_DOMAIN="${INTERNAL_DOMAIN}"
EMAIL_DOMAIN="${EMAIL_DOMAIN}"
EOF

cat <<EOF

✅ Saved org settings:

  DOCKER_ORG       = ${SAFE_ORG}
  INTERNAL_DOMAIN  = ${INTERNAL_DOMAIN}
  EMAIL_DOMAIN     = ${EMAIL_DOMAIN}

  → Stored in: ${ENV_FILE}

You can re-run this script any time to change the values.
The labs will reference these placeholders in policy examples.

EOF
